/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_administrador;

/**
 *
 * @author Carlos
 */
public class Vtn_Adopt extends javax.swing.JFrame {

    /**
     * Creates new form Vtn_Adopt
     */
    public Vtn_Adopt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inLastDateAdoptin = new javax.swing.JTextField();
        inStatusAdoptin = new javax.swing.JTextField();
        inTemaAdoptin = new javax.swing.JTextField();
        inInitialAdoptin = new javax.swing.JTextField();
        inCustomerAdoptin = new javax.swing.JTextField();
        inViewerAdoptin = new javax.swing.JTextField();
        inIDAdoptin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inDescriptionAdoptin = new javax.swing.JTextArea();
        BtnAddAdoptin = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 200));
        setMaximumSize(new java.awt.Dimension(650, 410));
        setMinimumSize(new java.awt.Dimension(650, 410));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 410));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Viewer in charge:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setText("Customer:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Initial date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setText("Description: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel6.setText("Tema:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setText("Status:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel8.setText("Last Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel10.setText("ID:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 30));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel11.setText("Add Adoptin Proposal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        getContentPane().add(inLastDateAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));
        getContentPane().add(inStatusAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, -1));
        getContentPane().add(inTemaAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, -1));
        getContentPane().add(inInitialAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, -1));
        getContentPane().add(inCustomerAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));
        getContentPane().add(inViewerAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));
        getContentPane().add(inIDAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, -1));

        inDescriptionAdoptin.setColumns(20);
        inDescriptionAdoptin.setRows(5);
        jScrollPane1.setViewportView(inDescriptionAdoptin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        BtnAddAdoptin.setText("Add Adoptin Proposal");
        getContentPane().add(BtnAddAdoptin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 170, -1));

        BtnBack.setText("Back");
        BtnBack.setToolTipText("");
        BtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBackMouseClicked(evt);
            }
        });
        getContentPane().add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 120, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoPantalla.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBackMouseClicked
        // TODO add your handling code here:
        Ventana_Principal back = new Ventana_Principal();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vtn_Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vtn_Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vtn_Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vtn_Adopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vtn_Adopt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddAdoptin;
    private javax.swing.JButton BtnBack;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField inCustomerAdoptin;
    private javax.swing.JTextArea inDescriptionAdoptin;
    private javax.swing.JTextField inIDAdoptin;
    private javax.swing.JTextField inInitialAdoptin;
    private javax.swing.JTextField inLastDateAdoptin;
    private javax.swing.JTextField inStatusAdoptin;
    private javax.swing.JTextField inTemaAdoptin;
    private javax.swing.JTextField inViewerAdoptin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
