/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_administrador;

/**
 *
 * @author Carlos
 */
public class Vtn_Pets extends javax.swing.JFrame {

    /**
     * Creates new form Vtn_Pets
     */
    public Vtn_Pets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        inDatePets = new javax.swing.JTextField();
        inStatusPets = new javax.swing.JTextField();
        inBreedPets = new javax.swing.JTextField();
        inSpeciesPets = new javax.swing.JTextField();
        inNamePets = new javax.swing.JTextField();
        inOwnerPets = new javax.swing.JTextField();
        inIDPets = new javax.swing.JTextField();
        inCastratePets = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        inDescriptionPets = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 200));
        setMaximumSize(new java.awt.Dimension(650, 410));
        setMinimumSize(new java.awt.Dimension(650, 410));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 410));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("Add Pets");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 90, 30));

        jLabel2.setText("Description:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Specie:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setText("Owner:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setText("Breed:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel7.setText("ID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel9.setText("Castrate:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel10.setText("AQUI VA LA IMAGEN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 150, 90));

        jLabel11.setText("Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel12.setText("Status:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButton1.setText("Add picture");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 130, -1));

        jButton2.setText("Add Pets");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 150, -1));

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 160, -1));

        inDatePets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inDatePetsActionPerformed(evt);
            }
        });
        getContentPane().add(inDatePets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 70, -1));

        inStatusPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inStatusPetsActionPerformed(evt);
            }
        });
        getContentPane().add(inStatusPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, -1));
        getContentPane().add(inBreedPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 70, -1));
        getContentPane().add(inSpeciesPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 70, -1));
        getContentPane().add(inNamePets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, -1));
        getContentPane().add(inOwnerPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));
        getContentPane().add(inIDPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, -1));

        inCastratePets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        getContentPane().add(inCastratePets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 70, -1));

        inDescriptionPets.setColumns(20);
        inDescriptionPets.setRows(5);
        jScrollPane1.setViewportView(inDescriptionPets);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoPantalla.png"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(650, 410));
        Fondo.setMinimumSize(new java.awt.Dimension(650, 410));
        Fondo.setPreferredSize(new java.awt.Dimension(650, 410));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inStatusPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inStatusPetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inStatusPetsActionPerformed

    private void inDatePetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inDatePetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inDatePetsActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Ventana_Principal back = new Ventana_Principal();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vtn_Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vtn_Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vtn_Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vtn_Pets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vtn_Pets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField inBreedPets;
    private javax.swing.JComboBox<String> inCastratePets;
    private javax.swing.JTextField inDatePets;
    private javax.swing.JTextArea inDescriptionPets;
    private javax.swing.JTextField inIDPets;
    private javax.swing.JTextField inNamePets;
    private javax.swing.JTextField inOwnerPets;
    private javax.swing.JTextField inSpeciesPets;
    private javax.swing.JTextField inStatusPets;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
